---
title: "create-WSI"
output: html_document
date: "2023-12-27"
---

```{r}
#library("rgdal")
library("raster")
library("sf")
library("leafsync")
library("dplyr")
library("ggplot2")
library("stars")
library(spatialEco)
library(spatstat.random)
library(data.table)
library(geoR)
library(RColorBrewer)
library(spdep)
library(spatialreg)
library(classInt)
#library(rgeos)
library(landscapemetrics)
library(nimble)
library(coda)
library(prism)
library(terra)
library(maps)
library(raster)

```

```{r}
wiShp<-st_read("./data/shapefiles/PLSS_Townships/PLSS_Townships.shp")
wiTwnshpShp <- st_read("./data/shapefiles/PLSS_Townships/PLSS_Townships.shp")
studyTwnshps <- read.table("./data/WITimeSeries-4-30-24")
studyTwnshps <- studyTwnshps %>% dplyr::select(uid) %>% filter(!duplicated(uid)) %>% as.vector()
# make uid
wiTwnshpShp$uid <- paste0(wiTwnshpShp$TWP, "-", wiTwnshpShp$RNG, "-", wiTwnshpShp$DIR_ALPHA)
wiTwnshpShp <- wiTwnshpShp %>% filter(uid %in% studyTwnshps$uid)
prism_set_dl_dir('D:\\prism-dat-f')
```

```{r, calculate WSI matrix, echo=FALSE}
months <- c(12, 1, 2, 3, 4)
# constants for calculating WSI
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
# need some spring date threshold
# these are for the WSI index; for year n-1
# NOTE start testing at 2017
# years<-c(seq(2001,2022,1))
years<-c(seq(2001, 2005, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                          "daily",
                                          years=2001))
# now we need to reproject these into the same CRS

# looking at only at Iowa County
#wiCountyShp<-subset(wiCountyShp,wiCountyShp$COUNTY_NAM == "Iowa")
wiShp.e<-projectExtent(wiCountyShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnshpShp <- wiTwnshpShp %>% mutate(uid = paste0(TWP, "-", RNG, "-", DIR_ALPHA))
wiTwnShpSpat<-project(as(wiTwnshpShp, "SpatVector"), crs(wiCountyShp))
wiTwnShpSpat<-as(wiTwnShpSpat,"Spatial")
# get the spat data into the same CRS
#wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")
cumPPT <- 0
wsiDat <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years)))
yearStrings <- c()
for(i in 1:(length(years)-1)){
  yearStrings[i] <- paste0(years[i], "-", years[i+1])
  }

names(wsiDat) <- c("uid", yearStrings)
k<-1
for(i in 1:(length(years)-1)){
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  # note can use prism_archive_verify
  # or prism_archive_clean
  # maybe need to change this to iterate over each day
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      wsiDat[j,]$uid <- wiTwnshpShp[j,]$uid
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        # check if any of the values are NA
        # maybe don't remove them
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)) ||
             any(is.null(pptVals), is.null(tminVals), is.null(tmaxVals)))){
          # note that PRISM data is reported in MM; 
          # average ppt for a given township for day k
          avgPPT <- mean(pptVals, na.rm=TRUE) / 10 # need CM divide by 10
          # average min. temp for a given township for day k 
          avgTMin <- mean(tminVals, na.rm=TRUE) 
          avgTMax <- mean(tmaxVals, na.rm=TRUE)
          avgTmp <- mean(c(tminVals, tmaxVals),na.rm=TRUE)
      if(avgPPT > 0 & avgTmp <= 0){
        cumPPT = cumPPT + avgPPT
      }
      # snow on the ground but above freezing
        
      # TODO: this is where factors such as latitude can be taken into account
      # could also take into account landscape factors here as well
      # note that the measurements are in mm for precip and C for temp
      # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
      # if(cumPPT > 0 & avgTmp > 0){
      #   # from Dawe and Boutin 2012 Journal of Wildlife Research
      #   meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
      #   cumPPT = cumPPT - meltFactor # some melt factor update later with lit found
      # }
      if((cumPPT >= pptThrshld & avgTMin >= tminThrshld) || 
         (cumPPT <= pptThrshld & avgTMin <= tminThrshld)){
            wsiDat[j,i+1] <- wsiDat[j,i+1] + 1
        }
      if(cumPPT > pptThrshld & avgTMin < tminThrshld){
            wsiDat[j,i+1] <- wsiDat[j,i+1] + 2
      }
      # in this case all  of the days in 
      # a particular township have been processed
          }
      }
      cumPPT <- 0
      }
}

write.table(wsiDat, "./data/wsi-test") # this is for testing as a check to make sure the time period is right
# save the WSI mat
# transform back to sf
wiTwnshpShp<-st_transform(wiTwnshpShp, st_crs(wiCountyStudy))
# create new variable
indx.i<-st_within(wiTwnshpShp, wiCountyStudy, sparse=FALSE)
indx<-which(indx.i, indx.i==FALSE)
wiTwnShpShpStudy<-wiTwnshpShp[- indx,]
wiTwnshpShp <- cbind(wiTwnshpShp, wsi.r)
# get rid of wistudyShp
plot(wiTwnshpShp[which(wiTwnshpShp$FID %in% wiTwnShpStudy$FID),], max.plot=20)
```
```{r create late-season WSI mat}
# TODO figure out how to save subsetted files

# norton et. al 2021 November, December, January
# norton et. al 2021 February, March
# constants for calculating WSI
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
earlySeasonStartDay<- '12-01' # november 1
earlySeasonEndDay <- '1-31' # may 10
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
# these are for the WSI index; for year n-1
# NOTE start testing at 2017
years<-c(seq(2001,2021,1))
# years.s<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                          "monthly",
                                          years=years))
# now we need to reproject these into the same CRS
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")

# get the spat data into the same CRS
wiTwnShpSpat<-spTransform(wiTwnShpSpat, crs(wiCountyShp))
cumPPT <- 0
wsi.mat.late <- matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years))
k<-1
for(i in 1:(length(years)-1)){
  
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  earlySeasonStartDate <- paste0(years[i], "-", earlySeasonStartDay)
  earlySeasonEndDate <- paste0(years[i] + 1, "-", earlySeasonEndDay)
  earlySeasonInterval<- abs(as.double(as.Date(as.character(earlySeasonStartDate), format="%Y-%m-%d")-
          as.Date(as.character(earlySeasonEndDate), format="%Y-%m-%d")))
 
  #if(exists)
  
  # note can use prism_archive_verify
  # or prism_archive_clean
  # maybe need to change this to iterate over each day
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        # need to check if any of the values are NA
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)))){
          # note that PRISM data is reported in MM; need CM divide by 10
          avgPPT <- mean(pptVals) / 10 # average ppt for a given township for day k
          avgTMin <- mean(tminVals) # average min. temp for a given township for day k 
          avgTMax <- mean(tmaxVals)
          avgTmp <- mean(c(tminVals, tmaxVals))
      if(avgPPT > 0 & avgTmp <= 0){
        cumPPT = cumPPT + avgPPT
      }
      # snow on the ground but above freezing
        
      # TODO: this is where factors such as latitude can be taken into account
      # could also take into account landscape factors here as well
      # note that the measurements are in mm for precip and C for temp
      # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
      
      if(cumPPT > 0 & avgTmp > 0){
        # from Dawe and Boutin 2012 Journal of Wildlife Research
        # meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
        cumPPT = cumPPT  # some melt factor update later with lit found
      }
      if(k >  earlySeasonInterval){
      if((cumPPT > pptThrshld) & avgPPT > pptThrshld){
            wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 1
        }
      if(cumPPT > pptThrshld & avgTMin < tminThrshld){
            wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 2
      }
      if(cumPPT < pptThrshld & avgTMin < tminThrshld){
        wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 1
      }
      # in this case all  of the days in 
      # a particular township have been processed
          }
      }
      cumPPT <- 0
      }
    }
}
write.table(wsi.mat.late, "./wsiMatLate")
```

```{r, calculate WSI matrix--snow pack only, echo=FALSE}
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
years<-c(seq(2001,2021,1))
# years.s<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                          "monthly",
                                          years=2001))
# now we need to reproject these into the same CRS
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")

# get the spat data into the same CRS
wiTwnShpSpat<-spTransform(wiTwnShpSpat, crs(wiShp))
cumPPT <- 0
wsi.mat.ppt <- matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years))
k<-1
for(i in 1:(length(years)-1)){
  
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        # need to check if any of the values are NA
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)))){
          # note that PRISM data is reported in MM; need CM divide by 10
          avgPPT <- mean(pptVals) / 10 # average ppt for a given township for day k
          avgTmp <- mean(c(tminVals, tmaxVals))
          if(avgPPT > 0 & avgTmp <= 0){
            cumPPT = cumPPT + avgPPT
          }
          # snow on the ground but above freezing
          # could also take into account landscape factors here as well
          # note that the measurements are in mm for precip and C for temp
          # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
        if(cumPPT > 0 & avgTmp > 0){
          # from Dawe and Boutin 2012 Journal of Wildlife Research
          meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
          cumPPT = cumPPT - meltFactor# some melt factor update later with lit found
        }
        if(cumPPT > pptThrshld){
          wsi.mat.ppt[j,i] <- wsi.mat.ppt[j,i] + 1
        }
      }
    }
    cumPPT <- 0
  }
}
write.table(wsi.mat.ppt, "./wsiMatPPT")
```

```{r, calculate WSI matrix, echo=FALSE}
months <- c(11, 12, 1, 2, 3, 4)
# constants for calculating WSI
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
# need some spring date threshold
# these are for the WSI index; for year n-1
# NOTE start testing at 2017
# years<-c(seq(2001,2022,1))
years<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                          "monthly",
                                          years=2001))
# now we need to reproject these into the same CRS

# looking at only at Iowa County
#wiCountyShp<-subset(wiCountyShp,wiCountyShp$COUNTY_NAM == "Iowa")
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnShpSpat<-project(as(wiTwnshpShp, "SpatVector"), crs(wiCountyShp))
# get the spat data into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")
cumPPT <- 0
wsi.mat <- matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years))
k<-1
for(i in 1:(length(years)-1)){
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  #if(exists)
  
  # note can use prism_archive_verify
  # or prism_archive_clean
  # maybe need to change this to iterate over each day
  solarRad <- pd_stack(prism_arch("Soltotal",
                                            "normal"))
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        # check if any of the values are NA
        # maybe don't remove them
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)) ||
             any(is.null(pptVals), is.null(tminVals), is.null(tmaxVals)))){
          # note that PRISM data is reported in MM; 
          # average ppt for a given township for day k
          avgPPT <- mean(pptVals, na.rm=TRUE) / 10 # need CM divide by 10
          # average min. temp for a given township for day k 
          avgTMin <- mean(tminVals) 
          avgTMax <- mean(tmaxVals)
          avgTmp <- mean(c(tminVals, tmaxVals))
      if(avgPPT > 0 & avgTmp <= 0){
        cumPPT = cumPPT + avgPPT
        
      }
      # snow on the ground but above freezing
        
      # TODO: this is where factors such as latitude can be taken into account
      # could also take into account landscape factors here as well
      # note that the measurements are in mm for precip and C for temp
      # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
      # if(cumPPT > 0 & avgTmp > 0){
      #   # from Dawe and Boutin 2012 Journal of Wildlife Research
      #   meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
      #   cumPPT = cumPPT - meltFactor # some melt factor update later with lit found
      # }
      if((cumPPT >= pptThrshld & avgTMin >= tminThrshld) || 
         (cumPPT <= pptThrshld & avgTMin <= tminThrshld)){
            wsi.mat[j,i] <- wsi.mat[j,i] + 1
        }
      if(cumPPT > pptThrshld & avgTMin < tminThrshld){
            wsi.mat[j,i] <- wsi.mat[j,i] + 2
      }
      # in this case all  of the days in 
      # a particular township have been processed
          }
      }
      cumPPT <- 0
      }
 }
# save the WSI mat
# transform back to sf
wiTwnshpShp<-st_transform(wiTwnshpShp, st_crs(wiCountyStudy))
# create new variable
indx.i<-st_within(wiTwnshpShp, wiCountyStudy, sparse=FALSE)
indx<-which(indx.i, indx.i==FALSE)
wiTwnShpShpStudy<-wiTwnshpShp[- indx,]
wiTwnshpShp <- cbind(wiTwnshpShp, wsi.r)
# get rid of wistudyShp
plot(wiTwnshpShp[which(wiTwnshpShp$FID %in% wiTwnShpStudy$FID),], max.plot=20)
```
```{r create late-season WSI mat}
# TODO figure out how to save subsetted files

# norton et. al 2021 November, December, January
# norton et. al 2021 February, March
# constants for calculating WSI
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
earlySeasonStartDay<- '12-01' # dec 1
earlySeasonEndDay <- '1-31' # may 10
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
# these are for the WSI index; for year n-1
# NOTE start testing at 2017
years<-c(seq(2001,2021,1))
# years.s<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                          "monthly",
                                          years=years))
# now we need to reproject these into the same CRS
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")

# get the spat data into the same CRS
wiTwnShpSpat<-spTransform(wiTwnShpSpat, crs(wiCountyShp))
cumPPT <- 0
wsi.mat.late <- matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years))
k<-1
for(i in 1:(length(years)-1)){
  
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  earlySeasonStartDate <- paste0(years[i], "-", earlySeasonStartDay)
  earlySeasonEndDate <- paste0(years[i] + 1, "-", earlySeasonEndDay)
  earlySeasonInterval<- abs(as.double(as.Date(as.character(earlySeasonStartDate), format="%Y-%m-%d")-
          as.Date(as.character(earlySeasonEndDate), format="%Y-%m-%d")))
 
  # note can use prism_archive_verify
  # or prism_archive_clean
  # maybe need to change this to iterate over each day
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        # need to check if any of the values are NA
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)))){
          # note that PRISM data is reported in MM; need CM divide by 10
          avgPPT <- mean(pptVals) / 10 # average ppt for a given township for day k
          avgTMin <- mean(tminVals) # average min. temp for a given township for day k 
          avgTMax <- mean(tmaxVals)
          avgTmp <- mean(c(tminVals, tmaxVals))
      if(avgPPT > 0 & avgTmp <= 0){
        cumPPT = cumPPT + avgPPT
      }
      # snow on the ground but above freezing
        
      # TODO: this is where factors such as latitude can be taken into account
      # could also take into account landscape factors here as well
      # note that the measurements are in mm for precip and C for temp
      # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
      
      if(cumPPT > 0 & avgTmp > 0){
        # from Dawe and Boutin 2012 Journal of Wildlife Research
        # meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
        cumPPT = cumPPT  # some melt factor update later with lit found
      }
      if(k >  earlySeasonInterval){
      if((cumPPT > pptThrshld) & avgPPT > pptThrshld){
            wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 1
        }
      if(cumPPT > pptThrshld & avgTMin < tminThrshld){
            wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 2
      }
      if(cumPPT < pptThrshld & avgTMin < tminThrshld){
        wsi.mat.late[j,i] <- wsi.mat.late[j,i] + 1
      }
      # in this case all  of the days in 
      # a particular township have been processed
          }
      }
      cumPPT <- 0
      }
    }
}
write.table(wsi.mat.late, "./wsiMatLate")
```

```{r, calculate WSI matrix--snow pack only, echo=FALSE}
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cited
# can set our month condition here for different measures of WSI
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
years<-c(seq(2000,2021,1))
# years.s<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
#pdStackRaw<-pd_stack(prism_archive_subset("ppt",
#                                          "monthly",
#                                          years=2001))
# now we need to reproject these into the same CRS
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)
# great now we have pdStackWI
# now we can crop the pdStack data into our study extent
pdStackWI<-terra::crop(pdStackRaw, wiShp.e)
# first let's get these into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")

# get the spat data into the same CRS
wiTwnShpSpat<-spTransform(wiTwnShpSpat, crs(wiShp))
cumPPT <- 0
wsi.mat.ppt <- matrix(0, nrow = nrow(wiTwnshpShp), ncol=length(years))
k<-1
for(i in 1:(length(years)-1)){
  
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    for(j in 1:length(ppt_by_twnshp)){
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        # need to check if any of the values are NA
        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        if(!(any(is.na(pptVals), is.na(tminVals), is.na(tmaxVals)))){
          # note that PRISM data is reported in MM; need CM divide by 10
          avgPPT <- mean(pptVals) / 10 # average ppt for a given township for day k
          avgTmp <- mean(c(tminVals, tmaxVals))
          if(avgPPT > 0 & avgTmp <= 0){
            cumPPT = cumPPT + avgPPT
          }
          # snow on the ground but above freezing
          # could also take into account landscape factors here as well
          # note that the measurements are in mm for precip and C for temp
          # https://prism.oregonstate.edu/FAQ/#:~:text=What%20units%20are%20the%20data,want%20maps%20in%20those%20units
        if(cumPPT > 0 & avgTmp > 0){
          # from Dawe and Boutin 2012 Journal of Wildlife Research
          meltFactor <- (1.88 + 0.007 * avgPPT) * (1.8 * avgTmp) + 1.27
          cumPPT = cumPPT - meltFactor# some melt factor update later with lit found
        }
        if(cumPPT > pptThrshld){
          wsi.mat.ppt[j,i] <- wsi.mat.ppt[j,i] + 1
        }
      }
    }
    cumPPT <- 0
  }
}
write.table(wsi.mat.ppt, "./wsiMatPPT")
```

```{r snowpack continuous}
minDay <- '12-01' # December 1
maxDay <- '04-30' # April 30
tminThrshld <- -17.7 # number used by MNDNR
tmaxThrshld <- 0
pptThrshld <- 38 # 38 cm cit
earlySeasonStartDay<- '12-01' # dec 1
earlySeasonEndDay <- '1-31' # may 10
years<-c(seq(2000,2022,1))
# years.s<-c(seq(2001, 2002, 1))
# DON'T DELETE; only for getting 
pdStackRaw<-pd_stack(prism_archive_subset("ppt",
                                           "daily",
                                           years=2000))
# now we need to reproject these into the same CRS
wiShp.e<-projectExtent(wiTwnshpShp, pdStackRaw)

# now grab our solar raster for each month

# m12 <- raster("D:\\prism-solar\\PRISM_soltotal_30yr_normal_4kmM3_12_bil\\PRISM_soltotal_30yr_normal_4kmM3_12_bil.bil") # december
# m1<- raster("D:\\prism-solar\\PRISM_soltotal_30yr_normal_4kmM3_01_bil\\PRISM_soltotal_30yr_normal_4kmM3_01_bil.bil") # january
# m2<- raster("D:\\prism-solar\\PRISM_soltotal_30yr_normal_4kmM3_02_bil\\PRISM_soltotal_30yr_normal_4kmM3_02_bil.bil") # february
# m3<-raster("D:\\prism-solar\\PRISM_soltotal_30yr_normal_4kmM3_03_bil\\PRISM_soltotal_30yr_normal_4kmM3_03_bil.bil") # march
# m4<-raster("D:\\prism-solar\\PRISM_soltotal_30yr_normal_4kmM3_04_bil\\PRISM_soltotal_30yr_normal_4kmM3_04_bil.bil") # april

# first let's get these into the same CRS
wiTwnShpSpat<-as(wiTwnshpShp, "Spatial")

# get the spat data into the same CRS
wiTwnShpSpat<-spTransform(wiTwnShpSpat, crs(wiShp))
cumPPT <- 0

# wsi snopack only
wsi.mat.ppt <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.ppt$uid <- wiTwnShpSpat$uid
names(wsi.mat.ppt) <- c(as.character(years), "uid")
wsi.mat.ppt<-wsi.mat.ppt[,c(ncol(wsi.mat.ppt),seq(2:(ncol(wsi.mat.ppt)-1)))] # switch order

# wsi temperature only
wsi.mat.temp <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.temp$uid <- wiTwnShpSpat$uid
names(wsi.mat.temp) <- c(as.character(years), "uid")
wsi.mat.temp<-wsi.mat.temp[,c(ncol(wsi.mat.temp),seq(2:(ncol(wsi.mat.temp)-1)))] # switch order

# gets the max snowpack for a given township
snopack.max <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
snopack.max$uid <- wiTwnShpSpat$uid
names(snopack.max) <- c(as.character(years), "uid")
snopack.max<-snopack.max[,c(ncol(snopack.max),seq(2:(ncol(snopack.max)-1)))] # switch order

# number of days with snowfall
snowfall.days <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
snowfall.days$uid <- wiTwnShpSpat$uid
 names(snowfall.days) <- c(as.character(years), "uid")
snowfall.days<-snowfall.days[,c(ncol(snowfall.days),seq(2:(ncol(snowfall.days)-1)))] # switch order

# ttl
wsi.mat.ttl <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.ttl$uid <- wiTwnShpSpat$uid

names(wsi.mat.ttl) <- c(as.character(years), "uid")
wsi.mat.ttl<-wsi.mat.ttl[,c(ncol(wsi.mat.ttl),seq(2:(ncol(wsi.mat.ttl)-1)))] # switch order

# early
wsi.mat.early <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.early$uid <- wiTwnShpSpat$uid
names(wsi.mat.early) <- c(as.character(years), "uid")
wsi.mat.early<-wsi.mat.early[,c(ncol(wsi.mat.early),seq(2:(ncol(wsi.mat.early)-1)))] # switch order

# late
wsi.mat.late <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.late$uid <- wiTwnShpSpat$uid

names(wsi.mat.late) <- c(as.character(years), "uid")
wsi.mat.late<-wsi.mat.late[,c(ncol(wsi.mat.late),seq(2:(ncol(wsi.mat.late)-1)))]
# switch order


wsi.mat.late <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
wsi.mat.late$uid <- wiTwnShpSpat$uid

names(wsi.mat.late) <- c(as.character(years), "uid")
wsi.mat.late<-wsi.mat.late[,c(ncol(wsi.mat.late),seq(2:(ncol(wsi.mat.late)-1)))]

# variability in snopack
ppt.var <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
ppt.var$uid <- wiTwnShpSpat$uid

names(ppt.var) <- c(as.character(years), "uid")
ppt.var<-ppt.var[,c(ncol(ppt.var),seq(2:(ncol(ppt.var)-1)))]

# number of snopack days

# number of days with no snow on ground
snopack.zero <- as.data.frame(matrix(0, nrow = nrow(wiTwnshpShp),
                                    ncol=length(years)))
snopack.zero$uid <- wiTwnShpSpat$uid
names(snopack.zero) <- c(as.character(years), "uid")
snopack.zero<-snopack.zero[,c(ncol(snopack.zero),seq(2:(ncol(snopack.zero)-1)))]

k<-1
for(i in 1:(length(years)-1)){
  minDate <- paste0(years[i], "-", minDay)
  maxDate <- paste0(years[i] + 1, "-", maxDay)
  # seasonal
  earlySeasonStartDate <- paste0(years[i], "-", earlySeasonStartDay)
  earlySeasonEndDate <- paste0(years[i] + 1, "-", earlySeasonEndDay)
  earlySeasonInterval<- abs(as.double(as.Date(as.character(earlySeasonStartDate), format="%Y-%m-%d")-
          as.Date(as.character(earlySeasonEndDate), format="%Y-%m-%d")))

  pptRaw<-pd_stack(prism_archive_subset("ppt",
                                        "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tmaxRaw<-pd_stack(prism_archive_subset("tmax",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  tminRaw<-pd_stack(prism_archive_subset("tmin",
                                         "daily",
                                         minDate=minDate,
                                         maxDate=maxDate))
  pptWI <- terra::crop(pptRaw, wiShp.e)
  tmaxWI<- terra::crop(tmaxRaw, wiShp.e)
  tminWI <- terra::crop(tminRaw, wiShp.e)
  ppt_by_twnshp <- terra::extract(pptWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmax_by_twnshp <- terra::extract(tmaxWI,
                                wiTwnShpSpat,
                                method="bilinear")
  tmin_by_twnshp <- terra::extract(tminWI,
                                wiTwnShpSpat,
                                method="bilinear")
    # index for the current day
    k <- 1
    # # get number of days in each month
    # daysm12 <- lubridate::days_in_month(as.Date(minDate, "%Y-%m-%d"))
    # daysm1 <- lubridate::days_in_month(as.Date(paste0(year[i] + 1,"-", '01',"-", "01"), "%Y-%m-%d"))
    # daysm2 <- lubridate::days_in_month(as.Date(paste0(year[i] + 1,"-", '02',"-", "01"), "%Y-%m-%d"))
    # daysm3 <- lubridate::days_in_month(as.Date(paste0(year[i] + 1,"-", '03',"-", "01"), "%Y-%m-%d"))
    # daysm4 <- lubridate::days_in_month(as.Date(maxDate, "%Y-%m-%d"))
    for(j in 1:length(ppt_by_twnshp)){
      cumPPT_vec <- c()
      for(k in 1:length(ppt_by_twnshp[[j]][1,])){
        # need to check if any of the values are NA

        pptVals<-as.vector(ppt_by_twnshp[[j]][,k])
        tminVals<-as.vector(tmin_by_twnshp[[j]][,k])
        tmaxVals<-as.vector(tmax_by_twnshp[[j]][,k])
        # note that PRISM data is reported in MM; need CM divide by 10
        avgPPT <- mean(pptVals,na.rm=TRUE) / 10 # average ppt for a given township for day k
        avgTmp <- mean(c(tminVals, tmaxVals),na.rm=TRUE)
        avgTMin <- mean(tminVals, na.rm=TRUE) 
        avgTMax <- mean(tmaxVals, na.rm=TRUE)
        if(avgPPT > 0 & avgTmp <= tmaxThrshld){
            cumPPT = cumPPT + avgPPT
            snowfall.days[j,i + 1] <- snowfall.days[j,i + 1] + 1
        }
        # check thresholds
        if(cumPPT > snopack.max[j,i+1]){
          snopack.max[j,i+1] <- cumPPT 
        }
        if(cumPPT == 0){
          snopack.zero[j,i+1] <- snopack.zero[j,i+1] + 1
        }
        if(cumPPT > 0 & avgTmp > tmaxThrshld){
          # using DDF formula from Zhang et al. 2021
          # never let cumPPT go below zero
          cumPPT = max(cumPPT - avgTmp, 0) # some melt factor update later with lit found
        }
        cumPPT_vec[k] <- cumPPT
        if(cumPPT > pptThrshld & (avgTMin < tminThrshld)){
          wsi.mat.temp[j,i+1] <- wsi.mat.temp[j,i+1] + 1
          wsi.mat.ppt[j,i+1] <- wsi.mat.ppt[j,i+1] + 1
          wsi.mat.ttl[j,i+1] <- wsi.mat.ttl[j,i+1] + 2
          wsi.mat.late[j,i+1] <- if_else(k > earlySeasonInterval,wsi.mat.late[j,i+1] + 2, wsi.mat.late[j,i+1])
          wsi.mat.early[j,i+1] <- if_else(k <= earlySeasonInterval,wsi.mat.early[j,i+1] + 2, wsi.mat.early[j,i+1])
        }
        if(cumPPT < pptThrshld & avgTMin < tminThrshld){
          wsi.mat.temp[j,i+1] <- wsi.mat.temp[j,i+1] + 1
          wsi.mat.ttl[j,i+1] <- wsi.mat.ttl[j,i+1] + 1
          wsi.mat.late[j,i+1] <- if_else(k > earlySeasonInterval,wsi.mat.late[j,i+1] + 1, wsi.mat.late[j,i+1])
          wsi.mat.early[j,i+1] <- if_else(k <= earlySeasonInterval,wsi.mat.early[j,i+1] + 1, wsi.mat.early[j,i+1])
        }
        if(cumPPT < pptThrshld & avgTMin < tminThrshld){
          wsi.mat.ttl[j,i+1] <- wsi.mat.ttl[j,i+1] + 1
          wsi.mat.late[j,i+1] <- if_else(k > earlySeasonInterval,wsi.mat.late[j,i+1] + 1, wsi.mat.late[j,i+1])
          wsi.mat.early[j,i+1] <- if_else(k <= earlySeasonInterval,wsi.mat.early[j,i+1] + 1, wsi.mat.early[j,i+1])
        }
      }
    cumPPT <- 0
    ppt.var[j,i+1] <- var(cumPPT_vec,na.rm=TRUE)
    }
}
```
```{r}
write.table(ppt.var,"./data/pptvar")
write.table(wsi.mat.early, "./data/wsi.mat.early")
write.table(wsi.mat.late, "./data/wsi.mat.late")
write.table(wsi.mat.ttl, "./data/wsi.mat.ttl")
write.table(snopack.zero, "./data/snopack.zero")
write.table(snopack.max, "./data/snopack.max")
write.table(wsi.mat.temp, "./data/wsi.mat.temp")
write.table(wsi.mat.ppt, "./data/wsi.mat.ppt")
```


