---
title: "prepare-data"
author: "Alexander Jack"
date: "2023-11-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=FALSE}
#library("rgdal")
library("raster")
library("sf")
library("leafsync")
library("dplyr")
library("ggplot2")
library("stars")
library(spatialEco)
library(spatstat.random)
library(data.table)
library(geoR)
library(RColorBrewer)
library(spdep)
library(spatialreg)
library(classInt)
#library(rgeos)
library(landscapemetrics)
library(nimble)
library(coda)
library(prism)
library(terra)
library(maps)
library(raster)
#library(rnoaa)
library(stringr)
library(tidyr)
```
```{r load data, echo=FALSE}
wiShp<-st_read("./data/shapefiles/Wisconsin_State_Boundary_24K/Wisconsin_State_Boundary_24K.shp")
wiTwnshpShp <- st_read("./data/shapefiles/PLSS_Townships/PLSS_Townships.shp")
# wiShp<-st_read("./data/shapefiles/PLSS_Townships/PLSS_Townships.shp")
wiCountyShp <- st_read("./data/shapefiles/County_Boundaries_24K/County_Boundaries_24K.shp")
# use this for setting the directory for prism
#prism_set_dl_dir("C:\\Users\\jackx\\Desktop\\prism-dat-f", create=FALSE)
# wiscland landcover raster
# nwiLC<-rast("./data/raster/wiscland2/wiscland2_dataset/level4/wiscland2_level4.tif")
# raw cwd data from google drive sheets
# cwd.dat.pos<-read.table(
#   "./data/wi-dat-cwd-pos.csv",
#   sep=",", header=TRUE)
# # raw cwd data from google drive sheets
# cwd.dat.analyzed<-read.table(
#   "./data/cwd-dat-num-analyzed.csv",
#   sep=",", header=TRUE)
# TODO also need to write the study shp
# cwdMatPos<-read.table("cwd.pos")
# cwdMatAnalyzed <- read.table("cwd.analyzed")
 WIDat<-read.table(
  "./data/WIData.csv",
  sep=",", header=TRUE)

 landscape <- read.table("./data/lcDat",
                         header=TRUE)
 
prismPPTStudy <- read.table("prism.ppt.study.area")
wsi.mat<-read.table("./data/wsicalculated") # this is the standard WSI used by WDNR 
wsi.mat.late <- read.table("./wsiMatLate")
year_min = 2001
year_max = 2021
wsi.years <- seq(year_min, year_max, 1)
studyCounties<-unique(WIDat$County) # get list of counties
station_radius = 30 # km 
#station_data=ghcnd_stat
#  (var="SNWD") # grab ghncd stations
# these calls can be used to get fresh PRISM data
# get_prism_dailys(type="ppt",
#                 minDate="2018-01-01",
#                 maxDate="2022-05-31", 
#                 keepZip = TRUE)
# get_prism_dailys(type="tmax",
#                  minDate="2000-11-01",
#                  maxDate="2022-05-31",
#                  keepZip = TRUE)
# get_prism_dailys(type="tmin",
#                  minDate="2000-11-01",
#                  maxDate="2022-05-31",
#                  keepZip = TRUE)
#prism_get_dl_dir(path="C:\\Users\\jackx022\\Desktop\\prism-dat-f")

```
```{r get list of all townships uids by county}
wiCountyShp<-st_transform(wiCountyShp, st_crs(wiTwnshpShp)) # project to same CRS
# get the uid field I use to get unique townshps
wiTwnshpShp <- wiTwnshpShp %>% mutate(uid = paste0(TWP, "-", RNG, "-", DIR_ALPHA))
# get the intersection
wiCountyTwnshps <- st_intersection(wiCountyShp, wiTwnshpShp)
```
```{r regress population data}
popDatTwnshp<-read.table("./data/popDat")
sample.spat <- wiCountyTwnshps %>% filter(COUNTY_NAM==c("Adams","Dane"))
landscape.filter <- landscape %>% filter(uid %in% sample.spat$uid)

landscape.hardwood <- landscape.filter %>% mutate(totalHardwood=(X4211 + X4212 + X4220 + X4231 + X4232 + X4233 + X4240 + X4251 + X4252 + X4300)/nCells)

landscape.hardwood <- landscape.hardwood %>% mutate(county = if_else(uid %in% adams.spat$uid, "Adams", "Dane"))
landscape.hardwood <- landscape.hardwood %>% group_by(county) %>% summarise(meanHardwo)
totalHardwood <- data.frame(county=studyCounties, totalHardwood=0)
ggplot(harvest.pop, aes(y=pop, x=harvest)) +
  geom_point()

```
```{r get prop forested array}
# count up the landscape tiles
landscape$county <- ""
for(i in 1:nrow(wiCountyTwnshps)){
  for(j in 1:nrow(landscape)){
    if(wiCountyTwnshps[i,]$uid == landscape[j,]$uid){
      landscape[j,]$county <- wiCountyTwnshps[i,]$COUNTY_NAM
    }
  }
}
for(i in 1:nrow(totalHardwood)){
  for(j in 1:nrow(landscape)){
    if(totalHardwood[i,]$county==landscape[j,]$county){
      landscape[j,]$totalHardwood = landscape[j,]$totalHardwood/totalHardwood[i,]$totalHardwood
    }
  }
}
# remove uids that got added
landscape <- landscape %>% filter(uid %in% unique(wiCountyTwnshps$uid))



hardwoods <- c("x4210", "x4211", "x4212", "x4220", "x4231",
               "x4232", "x4233", "x4240", "x4251", "x4252", "x42300")

# sum up all hardwood varieties
landscape <- landscape %>% mutate(totalHardwood=(X4211 + X4212 + X4220 + X4231 + X4232 + X4233 + X4240 + X4251 + X4252 + X4300))


totalHardwood <- data.frame(county=studyCounties, totalHardwood=0)
# sum up the total proportion of hardwood per twnshp
for(i in 1:nrow(totalHardwood)){
  for(j in 1:nrow(landscape)){
    if(totalHardwood[i,]$county==landscape[j,]$county){
      totalHardwood[i,]$totalHardwood = totalHardwood[i,]$totalHardwood + landscape[j,]$totalHardwood
    }
  }
}
# divide to get a proportion that will sum to 1
for(i in 1:nrow(totalHardwood)){
  for(j in 1:nrow(landscape)){
    if(totalHardwood[i,]$county==landscape[j,]$county){
      landscape[j,]$totalHardwood = landscape[j,]$totalHardwood/totalHardwood[i,]$totalHardwood
    }
  }
}

```


```{r}
#https://apps.dnr.wi.gov/deermetrics/DeerStats.aspx?R=2
# post-hunt pop. estimates
# 2002 - 2022
adams.harvest <-c(6506,8308,11860,8179,10262,9201,7428,5687,4382,4689,5601,5666,4248,5555,5514,5196,5573,4490,5611,4857,6020)
dane.harvest <- c(7616,7356,6659,5549,5117,6101,6084,5349,5649,4480,4694,3911,3899,4249,4186,3630,4369,3958,4948,3947,4473)
dane.harvest.2007<-c(6101,6084,5349,5649,4480,4694,3911,3899,4249,4186,3630,4369,3958,4948,3947,4473)
adams.harvest.2007<-c(9201,7428,5687,4382,4689,5601,5666,4248,5555,5514,5196,5573,4490,5611,4857,6020)




# 2007 - 2022
dane <- c(23900, 17500, 16800, 18900, 15400, 17100, 18900, 17400, 17700, 18500, 16700, 22300, 20700, 26200, 20800, 22700)
iowa <- c(25800, 18600, 18100, 20700, 16900, 17300, 18600, 20400, 21700, 24500, 20400, 26700, 22500, 27500, 20900, 20100)
sauk <- c(21700, 20200, 17900, 21200, 18200, 18700, 20500, 25200, 29600, 29500, 29000, 37100, 30200, 38900, 34400, 35100)
green <- c(11200, 7900, 8500, 8200, 7700, 8300, 9200, 8400, 9500, 10100, 8300, 11600, 10400, 13900, 11700, 11700)
columbia <- c(16900, 18200, 14200, 15100, 16100, 16300, 16000, 20400, 22700, 25400, 28400, 31300, 29900, 35400, 32500, 32700)
grant <- c(25600, 23000, 21200, 21600, 18600, 20800, 20400, 20700, 23000, 26300, 23800, 31600, 27800, 35400, 29400, 28700)
jefferson <- c(11800, 9200, 8600, 9200, 9100, 9600, 10100, 8500, 7900, 7000, 10100, 10900, 11000, 13700, 14000, 13400)
lafayette <- c(15200, 12700, 12400, 11400, 9400, 9300, 9000, 8700, 9900, 10300, 8300, 12400, 10200, 12300, 10400, 10600)
adams.cf <- c(19900, 16100, 10500, 13700, 12800, 14200, 13000, 15400, 16700, 19300, 18300, 19900, 15800,
              20000, 20000, 23200)
adams.cfarm <- c(2900, 2900, 3100, 3800, 4700, 4600, 4200, 4900, 5000, 5400, 5300, 6300, 6400, 8200, 7300, 8800)
marquette <- c(16100, 14200, 13500, 15100, 18400, 18500, 16300, 19800, 22300, 22400, 22900, 26300, 23400, 26900, 27800, 26300)
ozaukee <-c(1700, 1600, 1600, 1700, 2000, 2400, 2500, 3400, 4000, 4000, 3700, 3700, 4100, 4500, 4200, 4800)
walworth <-c(8500, 8500, 8800, 6800, 6800, 7000, 7100, 5300, 5200, 5900, 4500, 5800, 5900, 7700, 7300, 8600)
waukesha <- c(9600, 9300, 10100, 9000, 9900, 10800, 10700, 10300, 10200, 10600, 8000, 9200, 10800, 12000, 12000, 11800)
rock<-c(12100, 9200, 8600, 8800, 8800, 8900, 10000, 7400, 6800, 6000, 7000, 8900, 8800, 10800, 9800, 9800)
kenosha<-c(3700, 4000, 4000, 3200, 2600, 2800, 3000, 2200, 2100, 1900, 1200, 1600, 1500, 2000, 2000, 2300)
greenlake <-c(9000, 8200, 8700, 9800, 11700, 13000, 11000, 13100, 16100, 14500, 14700, 14800, 13200, 16200, 16500, 16300)
richland<-c(16800, 22100, 20200, 20300, 16600, 16600, 17900, 22300, 30400, 29500, 26200, 32300, 27100, 35900, 30000, 30600)
juneau<-c(16400, 13000, 8800, 11100, 10300, 11500, 10000, 7400, 8600, 9100, 11500, 12700, 8700, 10300, 10400, 1200)
vernon<-c(20000, 19500, 17600, 18800, 19400, 23000, 22200, 23400, 26800, 26600, 26300, 34700, 30100, 40200, 36500, 37000)
crawford<-c(18800, 17400, 16100, 14800, 16100, 18300, 16000, 16600, 20000, 1100, 15800, 21100, 16700, 23100, 21400, 22600)
dodge<-c(12200, 10500, 10900, 11500, 12100, 13000, 11000, 13400, 13700, 14100, 16500, 17700, 16700, 21500, 20300, 21700)
milwaulkee<-c(900,900,900,900,1100,1300,1400,600, 1000, 700, 900, 800, 1000, 1000, 900, 1000)
washington<-c(5700, 5200, 5300, 6000, 6400, 7500, 7300, 8000, 8200, 7700, 9600, 9500, 9300, 11300, 11400, 11900)
sheboygan<-c(6100, 4800, 4500, 5800, 6600, 7900, 7500, 6900, 7800, 8400, 10800, 11400, 9900, 12800, 12600, 12900)
racine<-c(4000, 4400, 4300, 3500, 2800, 3000, 3200, 2800, 3200, 3000, 2000, 2200, 2500, 3000, 3000, 3500)


adams <- adams.cf + adams.cfarm
# rbind things together

popDat <- data.frame(rbind(dane,
                iowa,
                sauk,
                green,
                columbia,
                grant,
                jefferson,
                lafayette,
                adams,
                marquette,
                ozaukee,
                walworth,
                waukesha,
                rock,
                kenosha,
                greenlake,
                richland,
                juneau,
                vernon,
                crawford,
                dodge,
                milwaulkee,
                washington,
                sheboygan,
                racine))

names(popDat) <- c(seq(2007, 2022, 1)) 

# now I need to intersect these data with the townships


adams <- data.frame(year=seq(2007,2022,1),pop=adams.pop, harvest=adams.harvest.2007)
```


```{r create deer population matrix}

popDatTwnshp <- data.frame(uid=wiCountyTwnshps$uid, county=tolower(str_replace(wiCountyTwnshps$COUNTY_NAM, " ", "")))
for(i in 1:length(studyYears)){ 
  popDatTwnshp[,paste0(studyYears[i])] <- 0
}
for(i in 1:nrow(popDatTwnshp)){
    for(j in 3:ncol(popDatTwnshp)){
            county <- popDatTwnshp[i,]$county
            uid <- popDatTwnshp[i,]$uid
            popDatTwnshp[i,j] <- round(popDat[county, j-2] *landscape[which(landscape$uid == uid),]$totalHardwood)      
      }
}
# summarize across duplicate uids in multiple counties
popDatTwnshpClean<-popDatTwnshp %>% 
  group_by(uid) %>% 
  summarise(across(.cols = starts_with("x"),.fns = sum))

write.table(popDatTwnshpClean,"./data/popDat") # save the table
popDatTwnshp<-read.table("./data/popDat")
```
```{r prepare wsi mat}
wiTwnshpShp <- cbind(wiTwnshpShp, wsi.mat)
wiTwnshpShp$uid <- paste0(wiTwnshpShp$TWP, "-", wiTwnshpShp$RNG, "-", wiTwnshpShp$DIR_ALPHA)
wsiDat <- as.data.frame(cbind(
  wiTwnshpShp$uid,
  wiTwnshpShp$V1,
  wiTwnshpShp$V2,
  wiTwnshpShp$V3,
  wiTwnshpShp$V4,
  wiTwnshpShp$V5,
  wiTwnshpShp$V6,
  wiTwnshpShp$V7,
  wiTwnshpShp$V8,
  wiTwnshpShp$V9,
  wiTwnshpShp$V10,
  wiTwnshpShp$V11,
  wiTwnshpShp$V12,
  wiTwnshpShp$V13,
  wiTwnshpShp$V14,
  wiTwnshpShp$V15,
  wiTwnshpShp$V16,
  wiTwnshpShp$V17,
  wiTwnshpShp$V18,
  wiTwnshpShp$V19,
  wiTwnshpShp$V20
))
# change naems of cols
names(wsiDat) <- c("uid",c(2002:2021)) # note that 2002 actually means 2001-2002 etc
# these are characters, need ints
wsiDat[,2] <- as.numeric(wsiDat[,2])
wsiDat[,3] <- as.numeric(wsiDat[,3])
wsiDat[,4] <- as.numeric(wsiDat[,4])
wsiDat[,5] <- as.numeric(wsiDat[,5])
wsiDat[,6] <- as.numeric(wsiDat[,6])
wsiDat[,7] <- as.numeric(wsiDat[,7])
wsiDat[,8] <- as.numeric(wsiDat[,8])
wsiDat[,9] <- as.numeric(wsiDat[,9])
wsiDat[,10] <- as.numeric(wsiDat[,10])
wsiDat[,11] <- as.numeric(wsiDat[,11])
wsiDat[,12] <- as.numeric(wsiDat[,12])
wsiDat[,13] <- as.numeric(wsiDat[,13])
wsiDat[,14] <- as.numeric(wsiDat[,14])
wsiDat[,15] <- as.numeric(wsiDat[,15])
wsiDat[,16] <- as.numeric(wsiDat[,16])
wsiDat[,17] <- as.numeric(wsiDat[,17])
wsiDat[,18] <- as.numeric(wsiDat[,18])
wsiDat[,19] <- as.numeric(wsiDat[,19])
wsiDat[,20] <- as.numeric(wsiDat[,20])
wsiDat[,21] <- as.numeric(wsiDat[,21])
# great get into long format
wsiDat.long <- as.data.frame(melt(wsiDat))
# rename vars
names(wsiDat.long) <- c("uid", "year", "wsi")
```

```{r get centroids}
# grab centroids for each township in WI
cents <- cbind(wiTwnshpShp$uid,wiTwnshpShp$geometry %>% st_centroid() %>% 
)
cents <- as.data.frame(cents)

names(cents) <- c("uid", "cent")
centsDat <- data.frame(uid=cents$uid, x=NA,y=NA)
for(i in 1:nrow(centsDat)){
  centsDat[i,]$x <- cents[i,]$cent[[1]][1]
  centsDat[i,]$y <- cents[i,]$cent[[1]][2]
}
centsDat$uid <- as.character(centsDat$uid)
```


```{r clean WIData}
nonSampYear<-c("1999-2001")
# change age to scalar
WIDatClean <- data.frame()
WIDatClean <- WIDat %>% mutate(Age = str_replace_all(Age, c("3" = "A", "9 to 11" = "A", "6 to 8" = "A", "4 to 5" = "A", "12\\+" = "A", "ADULT" = "A", "F" = "J", "1" = "Y", "2" = "Y")))
WIDatClean <- WIDatClean %>% mutate(Range.Direction = str_replace_all(Range.Direction, c("East" = "E", "West" = "W")))
# make UID to match previous analysis
WIDatClean <- WIDatClean %>% mutate(uid = paste0(Township, "-", Range, "-", Range.Direction))
# first aggregate over the cases

WIDatCleanSum <- WIDatClean %>% group_by(CWD.Year, County, uid, Test.Result, Hunter.Type, Age, Sex) %>% summarise(n=n(), .groups='drop')
WIDatCleanSum <- WIDatCleanSum[-c(which(WIDatCleanSum$CWD.Year=="1999-2001")),] # remove 1999-2001

WIDatClean <- WIDatClean %>% mutate(Hunter.Type = str_replace_all(Hunter.Type, c("Unknown Hunter" = "Citizen", "Citizen Hunter" = "Citizen", "Private contractor" = "non-Citizen", "USDA" = "non-Citizen", "WI DNR" = "non-Citizen", "ADULT" = "A", "F" = "J", "1" = "Y", "2" = "Y")))

WIDatClean <- WIDatClean %>% filter(Test.Result != "")
WIDatClean2<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"), nM = sum(Sex=="M"), nF = sum(Sex=="F"), nY=sum(Age=="Y"), nJ=sum(Age=="J"), nA=sum(Age=="A"), nUKAge=sum(Age==""), nUKSex=sum(Sex==""), nMY = sum(Sex=="M" & Age=="Y"), nMJ = sum(Sex=="M" & Age=="J"), nMA = sum(Sex=="M" & Age=="A"), nFJ = sum(Sex=="F" & Age=="J"), nFY = sum(Sex=="F" & Age=="Y"), nFA = sum(Sex=="F" & Age=="A"), nCit = sum(Hunter.Type=="Citizen"), nNCit = sum(Hunter.Type=="non-Citizen"), nHuntNA=sum(Hunter.Type==""), nPMY = sum(Sex=="M" & Age=="Y" & Test.Result=="Positive"), nPMJ = sum(Sex=="M" & Age=="J" & Test.Result=="Positive"), nPMA = sum(Sex=="M" & Age=="A"  & Test.Result=="Positive"), nPFJ = sum(Sex=="F" & Age=="J" & Test.Result=="Positive"), nPFY = sum(Sex=="F" & Age=="Y" & Test.Result=="Positive"), nPFA = sum(Sex=="F" & Age=="A" & Test.Result=="Positive"), .groups="drop")

# can also summarise and clean out non citizen hunters
# let's fix the dates quick
WIDatClean$kill.month <- ""
for(i in 1:nrow(WIDatClean)){
  WIDatClean[i,]$kill.month <- strsplit(WIDatClean[i,]$Kill.Date,"/")[[1]][1]  
}


############################################################################################################ this one separates by sex-age #################################

WIDat.hunt<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(kill.month %in% c(9,10,11,12)) %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"),
              nM = sum(Sex=="M"), nF = sum(Sex=="F"),
              nPM = sum(Sex=="M" & Test.Result=="Positive"),
              nPF = sum(Sex=="F" & Test.Result=="Positive"), .groups="drop")

# make sure that this was actually sampled
WIDatClean2<-WIDatClean2 %>% mutate(prev.M = if_else(nM > 0, round((nPM/nM)*1000), NA))
WIDatClean2<-WIDatClean2 %>% mutate(prev.F = if_else(nF > 0, round((nPF/nF)*1000), NA))
WIDatClean2<-WIDatClean2 %>% mutate(nPos = if_else(nSamp == 0 , NA, nPos))


# prevalence of age class among total sample
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.t.samp=if_else(is.na(nSamp), NA, round((nMA/nSamp)*1000)),
                                    MY.prev.t.samp=if_else(is.na(nSamp), NA, round((nMY/nSamp)*1000)),
                                    MJ.prev.t.samp=if_else(is.na(nSamp), NA, round((nMJ/nSamp)*1000)),
                                    FA.prev.t.samp=if_else(is.na(nSamp), NA, round((nFA/nSamp)*1000)),
                                    FY.prev.t.samp=if_else(is.na(nSamp), NA, round((nFY/nSamp)*1000)),
                                    FJ.prev.t.samp=if_else(is.na(nSamp), NA, round((nFJ/nSamp)*1000)))
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev=if_else(nMA==0, NA, round((nPMA/nMA)*1000)),
                                    MY.prev=if_else(nMY==0, NA, round((nPMY/nMY)*1000)), 
                                    MJ.prev=if_else(nMJ==0, NA, round((nPMJ/nMJ)*1000)),
                                    FA.prev=if_else(nFA==0, NA, round((nPFA/nFA)*1000)),
                                    FY.prev = if_else(nFY==0, NA, round((nPFY/nFY)*1000)),
                                    FJ.prev = if_else(nFJ==0, NA, round((nPFJ/nFJ)*1000)))
# positive prevalence
WIDatClean2<-WIDatClean2 %>% mutate(pos.prev=if_else(is.na(nSamp), NA, round((nPos/nSamp)*1000)))


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.sc = scale(MA.prev)[,1],
                                    MY.prev.sc = scale(MY.prev)[,1],
                                    MJ.prev.sc = scale(MJ.prev)[,1],
                                    FA.prev.sc = scale(FA.prev)[,1],
                                    FY.prev.sc = scale(FY.prev)[,1],
                                    FJ.prev.sc = scale(FJ.prev)[,1])


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.t.samp.sc = scale(MA.prev.t.samp)[,1],
                                    MY.prev.t.samp.sc = scale(MY.prev.t.samp)[,1],
                                    MJ.prev.t.samp.sc = scale(MJ.prev.t.samp)[,1],
                                    FA.prev.t.samp.sc = scale(FA.prev.t.samp)[,1],
                                    FY.prev.t.samp.sc = scale(FY.prev.t.samp)[,1],
                                    FJ.prev.t.samp.sc = scale(FJ.prev.t.samp)[,1])

# get the dataframe with unique combinations of year and twnshp

# filter out 1999-2001
names(WIDatClean2)[which(names(WIDatClean2) == "CWD.Year")] <- "year"  # rename column
WIDatClean2 <- WIDatClean2 %>% filter(year != nonSampYear)

WITimeSeries<-as.data.frame(expand.grid(uid=unique(WIDatClean2$uid), year=unique(WIDatClean2$year),group=c("M","F")))
WITimeSeries$uid <- as.character(WITimeSeries$uid)
WITimeSeries$year <- as.character(WITimeSeries$year)
WIDatClean2.long <- WIDatClean2 %>% dplyr::select(year,uid,prev.M,prev.F)
WIDatClean2.long.sample <- WIDatClean2 %>% dplyr::select(year,uid,nM, nF)
names(WIDatClean2.long.sample) <- c("year", "uid", "n.M", "n.F")
WIDatClean2.long <- WIDatClean2.long %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
             names_sep = "\\.")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
                          names_sep = "\\.")
names(WIDatClean2.long.sample) <- c("year", "uid", "value.", "group", "nSamp")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% dplyr::select("year", "uid", "group", "nSamp")
WITimeSeries2 <- merge(x=WITimeSeries, y=WIDatClean2.long, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean2.long.sample, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
names(WITimeSeries2) <- c("uid", "year", "group", "value.", "pos.prev", "nSamp")
WITimeSeries2 <- WITimeSeries2 %>% dplyr::select("year", "uid", "pos.prev", "group", "nSamp")

# now can merge WITimeSeries on wsi
WITimeSeries2 <- merge(x=WITimeSeries2, y=wsiDat.long, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
# now we can merge the centroids of the twnshps
WIDatClean5.merge <- WIDatClean5 %>% dplyr::select(uid, x, y, cv.diff, fd.diff) %>% filter(!duplicated(uid))
WITimeSeries2 <- WITimeSeries2 %>% filter(uid %in% WIDatClean5.merge$uid)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean5.merge, on.x=c(uid),
                       on.y=c(uid), all.x=TRUE)
# last step is to remove one year from the time series and cbind previous years positivty
pos.prev.t.minus.1.dat <- data.frame(year=WITimeSeries2$year,
                                     group=WITimeSeries2$group,
                                     uid = WITimeSeries2$uid,
                                     pos.prev.t.minus.1 = WITimeSeries2$pos.prev)
pos.prev.t.minus.1.dat <- pos.prev.t.minus.1.dat %>% filter(year < max(pos.prev.t.minus.1.dat$year)) # filter out last year in df
pos.prev.t.minus.1.dat$year <- as.numeric(pos.prev.t.minus.1.dat$year)
pos.prev.t.minus.1.dat$year <- pos.prev.t.minus.1.dat$year + 1
pos.prev.t.minus.1.dat$year <- as.character(pos.prev.t.minus.1.dat$year)
# remove 2002 from larger dataset
WITimeSeries2 <- WITimeSeries2 %>% filter(year > 2002)
# merge previous year into dataset
WITimeSeries2 <- merge(x=WITimeSeries2, y=pos.prev.t.minus.1.dat, on.x=c("uid", "year", "group"), on.y=c("uid", "year", "group"), all.x=TRUE)
WITimeSeries2$female <- 0
WITimeSeries2$male <- if_else(WITimeSeries2$group=="M", 1, 0)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-3-14-24")

WITimeSeries2$pos.prev.z <- if_else(WITimeSeries2$pos.prev > 0, 1, WITimeSeries2$pos.prev)
WITimeSeries2$pos.prev.c <- if_else(WITimeSeries2$pos.prev == 0, NA, WITimeSeries2$pos.prev)

WITimeSeries2$pos.prev.t.minus.1.z <- if_else(WITimeSeries2$pos.prev.t.minus.1 > 0,
                                              1, WITimeSeries2$pos.prev.t.minus.1)
WITimeSeries2$pos.prev.t.minus.1.c <- if_else(WITimeSeries2$pos.prev.t.minus.1 == 0,
                                              NA, WITimeSeries2$pos.prev.t.minus.1)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-4-16-24")
# merge this on uid and year to get other covariates
WITimeSeries4 <- merge(WITimeSeries3, WITimeSeries2, on.x=c('uid', "year"), on.y=c("uid", "year"))

WITimeSeries4 <- WITimeSeries4 %>% dplyr::select(year, uid, value., value, group, nSamp, x, y, x.sc, y.sc, wsi, wsi.sc, pos.prev.t.minus.1, pos.prev.t.minus.1.sc)
WITimeSeries4$MA <- if_else(WITimeSeries4$value=="MA",1,0)
WITimeSeries4$MY <- if_else(WITimeSeries4$value=="MY",1,0)
WITimeSeries4$MJ <- if_else(WITimeSeries4$value=="MJ",1,0)
WITimeSeries4$FA <- if_else(WITimeSeries4$value=="FA",1,0)
WITimeSeries4$FY <- if_else(WITimeSeries4$value=="FY",1,0)
WITimeSeries4$FJ <- if_else(WITimeSeries4$value=="FJ",1,0)
#names(WITimeSeries4)[3] <- "group"
names(WITimeSeries4)[4] <- "pos.prev"

write.table(WITimeSeries4,"./data/WITimeSeries-LONG")











############################################################################################################ this one separates by sex only#################################


WIDatClean.hunt<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(kill.month %in% c("9", "10", "11", "12")) %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"),
              nM = sum(Sex=="M"), nF = sum(Sex=="F"),
              nPM = sum(Sex=="M" & Test.Result=="Positive"),
              nPF = sum(Sex=="F" & Test.Result=="Positive"), .groups="drop")


# filter out those without proper UID

# make sure that this was actually sampled
WIDatClean2<-WIDatClean2 %>% mutate(nSamp = nPos+nNeg) %>%
  mutate(prev = if_else(nSamp > 0, round((nPos/(nSamp))*1000), NA)) %>%
  mutate(prop.M = if_else(nSamp > 0, (nM)/(nSamp), NA)) %>%
  mutate(prop.F = if_else(nSamp > 0, (nF)/(nSamp), NA))


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.sc = scale(MA.prev)[,1],
                                    MY.prev.sc = scale(MY.prev)[,1],
                                    MJ.prev.sc = scale(MJ.prev)[,1],
                                    FA.prev.sc = scale(FA.prev)[,1],
                                    FY.prev.sc = scale(FY.prev)[,1],
                                    FJ.prev.sc = scale(FJ.prev)[,1])


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.t.samp.sc = scale(MA.prev.t.samp)[,1],
                                    MY.prev.t.samp.sc = scale(MY.prev.t.samp)[,1],
                                    MJ.prev.t.samp.sc = scale(MJ.prev.t.samp)[,1],
                                    FA.prev.t.samp.sc = scale(FA.prev.t.samp)[,1],
                                    FY.prev.t.samp.sc = scale(FY.prev.t.samp)[,1],
                                    FJ.prev.t.samp.sc = scale(FJ.prev.t.samp)[,1])

# get the dataframe with unique combinations of year and twnshp

# filter out 1999-2001
names(WIDatClean2)[which(names(WIDatClean2) == "CWD.Year")] <- "year"  # rename column
WIDatClean2 <- WIDatClean2 %>% filter(year != nonSampYear)

WITimeSeries<-as.data.frame(expand.grid(uid=unique(WIDatClean2$uid), year=unique(WIDatClean2$year),group=c("M","F")))
WITimeSeries$uid <- as.character(WITimeSeries$uid)
WITimeSeries$year <- as.character(WITimeSeries$year)
WIDatClean2.long <- WIDatClean2 %>% dplyr::select(year,uid,prev.M,prev.F)
WIDatClean2.long.sample <- WIDatClean2 %>% dplyr::select(year,uid,nM, nF)
names(WIDatClean2.long.sample) <- c("year", "uid", "n.M", "n.F")
WIDatClean2.long <- WIDatClean2.long %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
             names_sep = "\\.")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
                          names_sep = "\\.")
names(WIDatClean2.long.sample) <- c("year", "uid", "value.", "group", "nSamp")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% dplyr::select("year", "uid", "group", "nSamp")
WITimeSeries2 <- merge(x=WITimeSeries, y=WIDatClean2.long, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean2.long.sample, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
names(WITimeSeries2) <- c("uid", "year", "group", "value.", "pos.prev", "nSamp")
WITimeSeries2 <- WITimeSeries2 %>% dplyr::select("year", "uid", "pos.prev", "group", "nSamp")

# now can merge WITimeSeries on wsi
WIDatClean4 <- merge(x=WIDatClean4, y=wsiDat.long, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
# now we can merge the centroids of the twnshps
WIDatClean5.merge <- WIDatClean5 %>% dplyr::select(uid, x, y, cv.diff, fd.diff) %>% filter(!duplicated(uid))
WITimeSeries2 <- WITimeSeries2 %>% filter(uid %in% WIDatClean5.merge$uid)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean5.merge, on.x=c(uid),
                       on.y=c(uid), all.x=TRUE)
# last step is to remove one year from the time series and cbind previous years positivty
pos.prev.t.minus.1.dat <- data.frame(year=WIDatClean4$year,
                                     uid=WIDatClean4$uid,
                                     pos.prev.t.minus.1 = WIDatClean4$prev)
pos.prev.t.minus.1.dat <- pos.prev.t.minus.1.dat %>% filter(year < max(pos.prev.t.minus.1.dat$year)) # filter out last year in df
pos.prev.t.minus.1.dat$year <- as.numeric(pos.prev.t.minus.1.dat$year)
pos.prev.t.minus.1.dat$year <- pos.prev.t.minus.1.dat$year + 1
pos.prev.t.minus.1.dat$year <- as.character(pos.prev.t.minus.1.dat$year)
# remove 2002 from larger dataset
WITimeSeries5 <- WIDatClean4 %>% filter(year > 2002)
# merge previous year into dataset
WITimeSeries2 <- merge(x=WITimeSeries5, y=pos.prev.t.minus.1.dat, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
WITimeSeries2$female <- 0
WITimeSeries2$male <- if_else(WITimeSeries2$group=="M", 1, 0)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-3-14-24")

WITimeSeries2$prev.z <- if_else(WITimeSeries2$prev > 0, 1, WITimeSeries2$prev)
WITimeSeries2$prev.c <- if_else(WITimeSeries2$prev == 0, NA, WITimeSeries2$prev)

WITimeSeries2$pos.prev.t.minus.1.z <- if_else(WITimeSeries2$pos.prev.t.minus.1 > 0,
                                              1, WITimeSeries2$pos.prev.t.minus.1)
WITimeSeries2$pos.prev.t.minus.1.c <- if_else(WITimeSeries2$pos.prev.t.minus.1 == 0,
                                              NA, WITimeSeries2$pos.prev.t.minus.1)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-4-16-24")
# merge this on uid and year to get other covariates
WITimeSeries4 <- merge(WITimeSeries3, WITimeSeries2, on.x=c('uid', "year"), on.y=c("uid", "year"))

WITimeSeries4 <- WITimeSeries4 %>% dplyr::select(year, uid, value., value, group, nSamp, x, y, x.sc, y.sc, wsi, wsi.sc, pos.prev.t.minus.1, pos.prev.t.minus.1.sc)
WITimeSeries4$MA <- if_else(WITimeSeries4$value=="MA",1,0)
WITimeSeries4$MY <- if_else(WITimeSeries4$value=="MY",1,0)
WITimeSeries4$MJ <- if_else(WITimeSeries4$value=="MJ",1,0)
WITimeSeries4$FA <- if_else(WITimeSeries4$value=="FA",1,0)
WITimeSeries4$FY <- if_else(WITimeSeries4$value=="FY",1,0)
WITimeSeries4$FJ <- if_else(WITimeSeries4$value=="FJ",1,0)
#names(WITimeSeries4)[3] <- "group"
names(WITimeSeries4)[4] <- "pos.prev"

write.table(WITimeSeries4,"./data/WITimeSeries-LONG")



# build male and female dfs

```

```{r sex and sick deer flag}


WIDatClean.hunt<-WIDatClean %>% 
    group_by(uid, CWD.Year, Sex, Sick.Deer.Flag) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(Kill.Date %in% c("9", "10", "11", "12")) %>%
    summarise(nPos = sum(Test.Result=="Positive"),
              nNeg=sum(Test.Result=="Negative"), .groups="drop")


# filter out those without proper UID

# make sure that this was actually sampled
WIDatClean2<-WIDatClean2 %>% mutate(prev.M = if_else(nM > 0, round((nPM/nM)*1000), NA))
WIDatClean2<-WIDatClean2 %>% mutate(prev.F = if_else(nF > 0, round((nPF/nF)*1000), NA))
WIDatClean2<-WIDatClean2 %>% mutate(nPos = if_else(nSamp == 0 , NA, nPos))


# prevalence of age class among total sample
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.t.samp=if_else(is.na(nSamp), NA, round((nMA/nSamp)*1000)),
                                    MY.prev.t.samp=if_else(is.na(nSamp), NA, round((nMY/nSamp)*1000)),
                                    MJ.prev.t.samp=if_else(is.na(nSamp), NA, round((nMJ/nSamp)*1000)),
                                    FA.prev.t.samp=if_else(is.na(nSamp), NA, round((nFA/nSamp)*1000)),
                                    FY.prev.t.samp=if_else(is.na(nSamp), NA, round((nFY/nSamp)*1000)),
                                    FJ.prev.t.samp=if_else(is.na(nSamp), NA, round((nFJ/nSamp)*1000)))
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev=if_else(nMA==0, NA, round((nPMA/nMA)*1000)),
                                    MY.prev=if_else(nMY==0, NA, round((nPMY/nMY)*1000)), 
                                    MJ.prev=if_else(nMJ==0, NA, round((nPMJ/nMJ)*1000)),
                                    FA.prev=if_else(nFA==0, NA, round((nPFA/nFA)*1000)),
                                    FY.prev = if_else(nFY==0, NA, round((nPFY/nFY)*1000)),
                                    FJ.prev = if_else(nFJ==0, NA, round((nPFJ/nFJ)*1000)))
# positive prevalence
WIDatClean2<-WIDatClean2 %>% mutate(pos.prev=if_else(is.na(nSamp), NA, round((nPos/nSamp)*1000)))


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.sc = scale(MA.prev)[,1],
                                    MY.prev.sc = scale(MY.prev)[,1],
                                    MJ.prev.sc = scale(MJ.prev)[,1],
                                    FA.prev.sc = scale(FA.prev)[,1],
                                    FY.prev.sc = scale(FY.prev)[,1],
                                    FJ.prev.sc = scale(FJ.prev)[,1])


# scale
WIDatClean2<-WIDatClean2 %>% mutate(MA.prev.t.samp.sc = scale(MA.prev.t.samp)[,1],
                                    MY.prev.t.samp.sc = scale(MY.prev.t.samp)[,1],
                                    MJ.prev.t.samp.sc = scale(MJ.prev.t.samp)[,1],
                                    FA.prev.t.samp.sc = scale(FA.prev.t.samp)[,1],
                                    FY.prev.t.samp.sc = scale(FY.prev.t.samp)[,1],
                                    FJ.prev.t.samp.sc = scale(FJ.prev.t.samp)[,1])

# get the dataframe with unique combinations of year and twnshp

# filter out 1999-2001
names(WIDatClean2)[which(names(WIDatClean2) == "CWD.Year")] <- "year"  # rename column
WIDatClean2 <- WIDatClean2 %>% filter(year != nonSampYear)

WITimeSeries<-as.data.frame(expand.grid(uid=unique(WIDatClean2$uid), year=unique(WIDatClean2$year),group=c("M","F")))
WITimeSeries$uid <- as.character(WITimeSeries$uid)
WITimeSeries$year <- as.character(WITimeSeries$year)
WIDatClean2.long <- WIDatClean2 %>% dplyr::select(year,uid,prev.M,prev.F)
WIDatClean2.long.sample <- WIDatClean2 %>% dplyr::select(year,uid,nM, nF)
names(WIDatClean2.long.sample) <- c("year", "uid", "n.M", "n.F")
WIDatClean2.long <- WIDatClean2.long %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
             names_sep = "\\.")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% pivot_longer(cols = -c(uid, year), 
             names_to = c("value.", "group"),
                          names_sep = "\\.")
names(WIDatClean2.long.sample) <- c("year", "uid", "value.", "group", "nSamp")
WIDatClean2.long.sample <- WIDatClean2.long.sample %>% dplyr::select("year", "uid", "group", "nSamp")
WITimeSeries2 <- merge(x=WITimeSeries, y=WIDatClean2.long, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean2.long.sample, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
names(WITimeSeries2) <- c("uid", "year", "group", "value.", "pos.prev", "nSamp")
WITimeSeries2 <- WITimeSeries2 %>% dplyr::select("year", "uid", "pos.prev", "group", "nSamp")

# now can merge WITimeSeries on wsi
WITimeSeries2 <- merge(x=WITimeSeries2, y=wsiDat.long, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
# now we can merge the centroids of the twnshps
WIDatClean5.merge <- WIDatClean5 %>% dplyr::select(uid, x, y, cv.diff, fd.diff) %>% filter(!duplicated(uid))
WITimeSeries2 <- WITimeSeries2 %>% filter(uid %in% WIDatClean5.merge$uid)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean5.merge, on.x=c(uid),
                       on.y=c(uid), all.x=TRUE)
# last step is to remove one year from the time series and cbind previous years positivty
pos.prev.t.minus.1.dat <- data.frame(year=WITimeSeries2$year,
                                     group=WITimeSeries2$group,
                                     uid = WITimeSeries2$uid,
                                     pos.prev.t.minus.1 = WITimeSeries2$pos.prev)
pos.prev.t.minus.1.dat <- pos.prev.t.minus.1.dat %>% filter(year < max(pos.prev.t.minus.1.dat$year)) # filter out last year in df
pos.prev.t.minus.1.dat$year <- as.numeric(pos.prev.t.minus.1.dat$year)
pos.prev.t.minus.1.dat$year <- pos.prev.t.minus.1.dat$year + 1
pos.prev.t.minus.1.dat$year <- as.character(pos.prev.t.minus.1.dat$year)
# remove 2002 from larger dataset
WITimeSeries2 <- WITimeSeries2 %>% filter(year > 2002)
# merge previous year into dataset
WITimeSeries2 <- merge(x=WITimeSeries2, y=pos.prev.t.minus.1.dat, on.x=c("uid", "year", "group"), on.y=c("uid", "year", "group"), all.x=TRUE)
WITimeSeries2$female <- 0
WITimeSeries2$male <- if_else(WITimeSeries2$group=="M", 1, 0)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-3-14-24")

WITimeSeries2$pos.prev.z <- if_else(WITimeSeries2$pos.prev > 0, 1, WITimeSeries2$pos.prev)
WITimeSeries2$pos.prev.c <- if_else(WITimeSeries2$pos.prev == 0, NA, WITimeSeries2$pos.prev)

WITimeSeries2$pos.prev.t.minus.1.z <- if_else(WITimeSeries2$pos.prev.t.minus.1 > 0,
                                              1, WITimeSeries2$pos.prev.t.minus.1)
WITimeSeries2$pos.prev.t.minus.1.c <- if_else(WITimeSeries2$pos.prev.t.minus.1 == 0,
                                              NA, WITimeSeries2$pos.prev.t.minus.1)
#write.table(WITimeSeries2,"./data/WITimeSeriesDat-4-16-24")
# merge this on uid and year to get other covariates
WITimeSeries4 <- merge(WITimeSeries3, WITimeSeries2, on.x=c('uid', "year"), on.y=c("uid", "year"))

WITimeSeries4 <- WITimeSeries4 %>% dplyr::select(year, uid, value., value, group, nSamp, x, y, x.sc, y.sc, wsi, wsi.sc, pos.prev.t.minus.1, pos.prev.t.minus.1.sc)
WITimeSeries4$MA <- if_else(WITimeSeries4$value=="MA",1,0)
WITimeSeries4$MY <- if_else(WITimeSeries4$value=="MY",1,0)
WITimeSeries4$MJ <- if_else(WITimeSeries4$value=="MJ",1,0)
WITimeSeries4$FA <- if_else(WITimeSeries4$value=="FA",1,0)
WITimeSeries4$FY <- if_else(WITimeSeries4$value=="FY",1,0)
WITimeSeries4$FJ <- if_else(WITimeSeries4$value=="FJ",1,0)
#names(WITimeSeries4)[3] <- "group"
names(WITimeSeries4)[4] <- "pos.prev"

write.table(WITimeSeries4,"./data/WITimeSeries-LONG")


```

```{r male and female models}
WIDat.hunt.m<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(kill.month %in% c(9,10,11,12)) %>% filter(CWD.Year != "1999-2001") %>%
    filter(Sex=="M") %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"), .groups="drop")
WIDat.hunt.m$CWD.Year <- as.numeric(WIDat.hunt.m$CWD.Year)
WIDat.hunt.m <- WIDat.hunt.m %>% filter(uid %in% j$uid)
names(WIDat.hunt.m)[which(names(WIDat.hunt.m) == 'CWD.Year')] <- "year"
WIDat.hunt.m <- merge(WIDat.hunt.m, j, on.x=c(uid, year), on.y=c(uid,year), all.y=TRUE)
WIDat.hunt.m$nSamp <- WIDat.hunt.m$nPos + WIDat.hunt.m$nNeg
WIDat.hunt.m$nSamp <- if_else(is.na(WIDat.hunt.m$nSamp), 0, WIDat.hunt.m$nSamp)
WIDat.hunt.m <- merge(x=WIDat.hunt.m, y=wsiDat.long, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
WIDat.hunt.m<-WIDat.hunt.m %>% mutate(prev = if_else(nSamp > 0, round((nPos/nSamp)*1000), NA))
WIDat.hunt.m$prev.z <- if_else(WIDat.hunt.m$prev > 0, 1, WIDat.hunt.m$prev)
WIDat.hunt.m$prev.c <- if_else(WIDat.hunt.m$prev == 0, NA, WIDat.hunt.m$prev)
write.table(WIDat.hunt.m, "./data/WIDatSexSplitM")

WIDat.hunt.f<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(kill.month %in% c(9,10,11,12)) %>%
    filter(Sex=="F") %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"), .groups="drop")
WIDat.hunt.f$CWD.Year <- as.numeric(WIDat.hunt.f$CWD.Year)
WIDat.hunt.f <- WIDat.hunt.f %>% filter(uid %in% j$uid)
names(WIDat.hunt.f)[which(names(WIDat.hunt.f) == 'CWD.Year')] <- "year"
WIDat.hunt.f <- merge(WIDat.hunt.f, j, on.x=c(uid, year), on.y=c(uid,year), all.y=TRUE)
WIDat.hunt.f$nSamp <- WIDat.hunt.f$nPos + WIDat.hunt.f$nNeg 
WIDat.hunt.f$nSamp <- if_else(is.na(WIDat.hunt.f$nSamp), 0, WIDat.hunt.f$nSamp)
WIDat.hunt.f <- merge(x=WIDat.hunt.f, y=wsiDat.long, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
WIDat.hunt.f<-WIDat.hunt.f %>% mutate(prev = if_else(nSamp > 0, round((nPos/nSamp)*1000), NA))
WIDat.hunt.f$prev.z <- if_else(WIDat.hunt.f$prev > 0, 1, WIDat.hunt.f$prev)
WIDat.hunt.f$prev.c <- if_else(WIDat.hunt.f$prev == 0, NA, WIDat.hunt.f$prev)
write.table(WIDat.hunt.f, "./data/WIDatSexSplitF")
```
```{r male and female models}
WIDat.hunt.y<-WIDatClean %>% 
    group_by(uid, CWD.Year) %>% filter(Hunter.Type=="Citizen Hunter") %>%
    filter(kill.month %in% c(9,10,11,12)) %>% filter(CWD.Year != "1999-2001") %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"), nM = sum(Sex=="M"), nF = sum(Sex=="F"), nMY = sum(Sex=="M" & Age=="Y"), nMA = sum(Sex=="M" & Age=="A"), nFY = sum(Sex=="F" & Age=="Y"), nFA = sum(Sex=="F" & Age=="A"), nPMY = sum(Sex=="M" & Age=="Y" & Test.Result=="Positive"), nPMA = sum(Sex=="M" & Age=="A"  & Test.Result=="Positive"), nPFY = sum(Sex=="F" & Age=="Y" & Test.Result=="Positive"), nPFA = sum(Sex=="F" & Age=="A" & Test.Result=="Positive"), .groups="drop")

template <- as.data.frame(expand.grid(unique(WIDat.hunt.y$uid), as.character(unique(WIDat.hunt.y$CWD.Year))))
names(template) <- c("uid", "year")
template$year <- as.numeric(as.character(template$year))
template <- template %>% filter(uid %in% j$uid) %>% filter(year < 2022)
names(WIDat.hunt.y)[which(names(WIDat.hunt.y) == 'CWD.Year')] <- "year"
WIDat.hunt.y$year <- as.numeric(WIDat.hunt.y$year)
WIDat.hunt.y <- merge(WIDat.hunt.y, template, on.x=c("uid", "year"), on.y=c("uid","year"),all.y=TRUE)
WIDat.hunt.y<-WIDat.hunt.y %>% mutate(MA.prev=if_else(nMA==0, NA, round((nPMA/nMA)*10000)),
                                    MY.prev=if_else(nMY==0, NA, round((nPMY/nMY)*10000)),
                                    FA.prev=if_else(nFA==0, NA, round((nPFA/nFA)*10000)),
                                    FY.prev=if_else(nFY==0, NA, round((nPFY/nFY)*10000)))  

j <- j %>% filter(male==1) %>% dplyr::select(uid,x,y,fd.diff,cv.diff) %>% filter(!duplicated(uid))
WIDat.hunt.y <- WIDat.hunt.y %>% filter(uid %in% j$uid)
WIDat.hunt.y <- merge(WIDat.hunt.y, j, on.x=c(uid), on.y=c(uid), all.y=TRUE)
WIDat.hunt.y$year <- as.numeric(WIDat.hunt.y$year)
WIDat.hunt.y$nSamp <- WIDat.hunt.y$nPos + WIDat.hunt.y$nNeg
WIDat.hunt.y$nSamp <- if_else(is.na(WIDat.hunt.y$nSamp), 0, WIDat.hunt.y$nSamp)
WIDat.hunt.y <- merge(x=WIDat.hunt.y, y=wsiDat.long, on.x=c(uid, year),
                      on.y=c(uid, year), all.x=TRUE)


# last step is to remove one year from the time series and cbind previous years positivty
pos.prev.t.minus.1.dat <- data.frame(year=WIDat.hunt.y$year,
                                     uid = WIDat.hunt.y$uid,
                                     nPos.t.minus.1 = WIDat.hunt.y$nPos)
pos.prev.t.minus.1.dat <- pos.prev.t.minus.1.dat %>% filter(year < max(pos.prev.t.minus.1.dat$year)) 
# filter out last year in df
pos.prev.t.minus.1.dat$year <- as.numeric(pos.prev.t.minus.1.dat$year)
pos.prev.t.minus.1.dat$year <- pos.prev.t.minus.1.dat$year + 1
pos.prev.t.minus.1.dat$year <- as.character(pos.prev.t.minus.1.dat$year)
# remove 2002 from larger dataset
WIDat.hunt.y <- WIDat.hunt.y %>% filter(year > 2002)
# merge previous year into dataset
WIDat.hunt.y <- merge(x=WIDat.hunt.y, y=pos.prev.t.minus.1.dat, on.x=c("uid", "year"), on.y=c("uid", "year"), all.x=TRUE)
names(WIDatClean2.long.sample) <- c("year", "uid", "value.", "group", "nSamp")

WIDatClean2.long.sample <- WIDatClean2.long.sample %>% dplyr::select("year", "uid", "group", "nSamp")

WITimeSeries2 <- merge(x=WITimeSeries, y=WIDatClean2.long, on.x=c("uid", "year", ""),
                       on.y=c("uid", "year", "MA.prev"), all.x=TRUE)
WITimeSeries2 <- merge(x=WITimeSeries2, y=WIDatClean2.long.sample, on.x=c("uid", "year", "group"),
                       on.y=c("uid", "year", "group"), all.x=TRUE)
names(WITimeSeries2) <- c("uid", "year", "group", "value.", "pos.prev", "nSamp")
WITimeSeries2 <- WITimeSeries2 %>% dplyr::select("year", "uid", "pos.prev", "group", "nSamp")
    group_by(uid, CWD.Year) %>%
    summarise(nPos = sum(Test.Result=="Positive"), nNeg=sum(Test.Result=="Negative"), nM = sum(Sex=="M"), nF = sum(Sex=="F"), nY=sum(Age=="Y"), nJ=sum(Age=="J"), nA=sum(Age=="A"), nUKAge=sum(Age==""), nUKSex=sum(Sex==""), nMY = sum(Sex=="M" & Age=="Y"), nMJ = sum(Sex=="M" & Age=="J"), nMA = sum(Sex=="M" & Age=="A"), nFJ = sum(Sex=="F" & Age=="J"), nFY = sum(Sex=="F" & Age=="Y"), nFA = sum(Sex=="F" & Age=="A"), nCit = sum(Hunter.Type=="Citizen"), nNCit = sum(Hunter.Type=="non-Citizen"), nHuntNA=sum(Hunter.Type==""), nPMY = sum(Sex=="M" & Age=="Y" & Test.Result=="Positive"), nPMJ = sum(Sex=="M" & Age=="J" & Test.Result=="Positive"), nPMA = sum(Sex=="M" & Age=="A"  & Test.Result=="Positive"), nPFJ = sum(Sex=="F" & Age=="J" & Test.Result=="Positive"), nPFY = sum(Sex=="F" & Age=="Y" & Test.Result=="Positive"), nPFA = sum(Sex=="F" & Age=="A" & Test.Result=="Positive"), .groups="drop")
write.table(WIDat.hunt.y, "./data/WIDatPropAgeClassSex")

WIDat.hunt.y$nSamp <- if_else(WIDat.hunt.y$nFA)
WIDat.hunt.y$prop.FA <- if_else(WIDat.hunt.y$nFA==0, NA, )

names(WIDatClean2.long.sample) <- c("year", "FA", "FY", "MY", "MA")
WIDat.hunt.y.d <- WIDat.hunt.y %>% dplyr::select(uid, year, nPMA,nMA,nMY, nPMY,nFA, nPFA,nFY, nPFY,x, y, fd.diff, cv.diff, wsi)
WIDatClean2.long.2 <- WIDat.hunt.y.d %>% 
  pivot_longer(cols = -c(uid, year, cv.diff, wsi, fd.diff, x, y, wsi)) %>%
group_by(c("nMA", "nPMA"), c("nPMY","nMY"),c('nPFA', "nFA"), c("nPFY", "nFY"))
                                                     )
names(WIDatClean2.long) <- c("uid","year","x","y","fd.diff","cv.diff","wsi","group","r","prev")
WIDatClean2.long$MA <- 0
WIDatClean2.long$MY <- if_else(WIDatClean2.long$group=="MY", 1, 0)
WIDatClean2.long$FA <- if_else(WIDatClean2.long$group=="FA", 1, 0)
WIDatClean2.long$FY <- if_else(WIDatClean2.long$group=="FY", 1, 0)
write.table(WIDatClean2.long, "./data/WIDatPropAgeClassSex")
```


```{r create summary data figures}

WIDatClean2 <- WIDatClean2 %>% filter(uid %in% wiTwnshpStudy$uid)
WIDatClean2 <- WIDatClean2 %>% filter(! CWD.Year %in% nonSampYear)
# rename data
names(WIDatClean2)[which(names(WIDatClean2) == 'CWD.Year')] <- "year"
# melt that sheit

# WIDatClean.long <- melt(WIDatClean2, id.vars=c("nMA", "nMY", "nMJ", "nFA", "nFY", "nFJ"))
sum(WIDatClean2$nSamp, na.rm=TRUE) # number of samples 208327
sexSummary <- WIDatClean2 %>% group_by("nMA", "nMY", "nMJ", "nFA", "nFY", "nFJ") %>% summarise(n=n())
sum(WIDatClean2$nMA, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)
sum(WIDatClean2$nMY, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)
sum(WIDatClean2$nMJ, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)
sum(WIDatClean2$nFA, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)
sum(WIDatClean2$nFY, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)
sum(WIDatClean2$nFJ, na.rm=TRUE)/sum(WIDatClean2$nSamp, na.rm=TRUE)

names(WIDatClean2)[which(names(WIDatClean2) == "CWD.Year")] <- "year"  # rename column
WIDatClean.long <- WIDatClean2 %>% group_by(year) %>% summarise(nPMA = sum(nPMA)/sum(nMA),                                                             nPMY=sum(nPMY)/sum(nMY), nPMJ= sum(nPMJ)/sum(nMJ), nPFA=sum(nPFA)/sum(nFA), nPFY=sum(nPFY)/sum(nFY),nPFJ = sum(nPFJ)/sum(nFJ))
                                                             #nPFJ), nPMY, nPMJ, nPFA, nPFY, 
WIDatClean.long <- WIDatClean.long %>% group_by(year, nPMA, nPMY, nPMJ, nPFA, nPFY, nPFJ, nSamp)
WIDatCleanAnnual <- WIDatClean2 %>% group_by(c("year", "nPMA", "nPM",
                                             "nPMJ", "nPFA", "nPFY",
                                             "nPFJ", "nSamp"))
WIDatSamp <- WIDatClean2 %>% group_by(year) %>% summarise(nSamp=sum(nSamp,na.rm=TRUE))

WIDatClean.long <- melt(WIDatClean.long) 
names(WIDatClean.long) <- c("year", "group", "value")
ggplot(data = WIDatClean.long) +
  geom_line(aes(x=year, y=value, group=group, color=group)) + 
theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black"), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + # get rid of grey 
ggtitle("CWD+ By Group") + 
theme(plot.title = element_text(hjust = 0.5))



```
```{r display annual variation in sampling effort}
WIDatAnnualVar <- WIDat %>% filter(!(CWD.Year %in% nonSampYear))
# plot bar graph
ggplot(WIDatAnnualVar, aes(x=CWD.Year)) +
  geom_bar(show.legend = FALSE) +
  ylab("Log(Rate Positive/10000 images)") +
  xlab("site ID") +
  ggtitle("Encounter Rate per 10,000 images")
```

```{r examine spatial differences in sampling effort}
WIDatSampleSpatial <- WIDatClean %>% group_by(uid) %>% summarise(numSamp=n())

wiTwnshpShpStudySpatialSample <- wiTwnshpStudy
wiTwnshpShpStudySpatialSample$numSamp <- 0
for(i in 1:nrow(wiTwnshpShpStudySpatialSample)){
  for(j in 1:nrow(WIDatSampleSpatial)){
    if(wiTwnshpShpStudySpatialSample[i,]$uid == WIDatSampleSpatial[j,]$uid){
      wiTwnshpShpStudySpatialSample[i,]$numSamp <- WIDatSampleSpatial[j,]$numSamp
    }
  }
}

wiTwn

wiTwnshpShpStudySpatialSample$numSamp <- log(wiTwnshpShpStudySpatialSample$numSamp + 1)
plot(wiTwnshpShpStudySpatialSample[,6], main="Log Normalized Number of Samples (2007-2022)") 
```

```{r}
wiDatKillMethod <- WIDatClean %>% group_by(Hunter.Type) %>% summarise(num=n())
wiDatKillMethod
wiDatSex <- WIDatClean %>% group_by(Sex)%>% summarise(num=n())
wiDatSex
wiDatSexPositivity <- WIDatClean %>% group_by(Sex, Test.Result) %>% filter(Sex=='M' || Sex=='F') %>% summarise(num=n(), .groups="keep")
# check positivity rate
wiDatSexPositivityWide<-melt(wiDatSexPositivity, idvar="Sex", measure.vars = "Test.Result")

wiDatSex <- data.frame(sex=c("M","F"), rate=0)

for(i in 1:nrow(wiDatSexPositivity)){
  for(j in 1:nrow(wiDatSex)){
    if(wiDatSex[j,]$sex==wiDatSexPositivity[i,]$Sex){
      wiDatSex[j,]$rate = wiDatSexPositivity[i,]$num + wiDatSex[j,]$rate
    }
  }
}
wiDatSex[which(wiDatSex$sex=='M'),]$rate = wiDatSexPositivity[which(wiDatSexPositivity$Sex=='M' & wiDatSexPositivity$Test.Result=='Positive'),]$num/wiDatSex[which(wiDatSex$sex=='M'),]$rate
wiDatSex[which(wiDatSex$sex=='F'),]$rate = wiDatSexPositivity[which(wiDatSexPositivity$Sex=='F' & wiDatSexPositivity$Test.Result=='Positive'),]$num/wiDatSex[which(wiDatSex$sex=='F'),]$rate
wiDatSex
```


```{r, rnoaa}
wsMatMean <- matrix(0, nrow=nrow(wiStudyShp), ncol=length(seq(year_min, year_max, 1)))
wsMatMax <- matrix(0, nrow=nrow(wiStudyShp), ncol=length(seq(year_min, year_max, 1)))
# iterate thru the study sf object of twnshps in study area
for(i in 1:nrow(wiStudyShp)){
  geo<-wiStudyShp[i,]$geometry
  uid<-wiStudyShp[i,]$uid
  # SNWD is the element for snowdepth
  # SNWD is reported in mm
  # VALUE1 is the value on the first day of the month (missing = -9999)
  centroid<-st_transform(st_centroid(geo, resolution="20m"), '+proj=longlat +nodefs')
  # create centroid object id, lat ,lon
  cent <- data.frame(id=wiStudyShp[i,]$uid,latitude=unlist(centroid,1)[2], longitude=unlist(centroid,2)[1])
  nearStations<-meteo_nearby_stations(cent,var="snwd", station_data=station_data,radius=station_radius, year_min=2001, year_max=2022)
  # creates character vector of nearby station ids
  nearStationIDs <- c(get(uid,nearStations)[,1]) 
  monitors <- meteo_pull_monitors(nearStationIDs, date_min="2001-12-01", date_max="2022-04-30")
  monitors<-monitors %>% select(date,snwd) %>% na.omit() %>% group_by(date) %>% mutate(sumsnwd = sum(snwd)) %>% mutate(numsnwd = n()) %>%
  mutate(year=as.numeric(strsplit(as.character(date), "-")[[1]][1])) %>% mutate(month=as.numeric(strsplit(as.character(date), "-")[[1]][2])) %>% mutate(day=as.numeric(strsplit(as.character(date), "-")[[1]][3]))
  # generate average snow depth
  # divide by 10 to convert to CM 
   monitors<-monitors %>% select(date,year,month,day,sumsnwd,numsnwd) %>%
    mutate(avgsnwd=(sumsnwd/numsnwd)/10)
  # get average daily SNWD
   # filter by months
   monitors <- monitors %>% filter(month %in% c(1,2,3,4,5,12))
  # get a list of objects to remove
  # create an object for each near station
   for(j in 2:length(wsi.years)){
      monitorsYearPrior<-monitors %>% filter(month %in% c(12) & year==wsi.years[j-1])
      monitorsCurrentYear<-monitors %>% filter(month %in% c(1,2,3,4,5) & year==wsi.years[j])
      wsMatMean[i,j] <- mean(c(monitorsYearPrior$avgsnwd, monitorsCurrentYear$avgsnwd))
      wsMatMax[i,j] <- max(c(monitorsYearPrior$avgsnwd, monitorsCurrentYear$avgsnwd))
  }
}
```
```{r test for excessive zeroes}

fit.nbin <- MASS::glm.nb(nPos~prop.M+ log(nSamp+1) + cv.diff+idtime+scale(wsi),data=f)

# Number of simulations
  nsims<-10000

# Set up matrix to hold goodness-of-fit statistics
  zeros.sim<-matrix(NA, nsims, 1)
  nobs<-nrow(f) # number of observations
  
# Extract the estimated coefficients and their asymptotic variance/covariance matrix  
# Use these values to generate nsims new beta's  
  beta.hat<-MASS::mvrnorm(nsims, coef(fit.nbin), vcov(fit.nbin))
  theta.hat<-rnorm(nsims, fit.nbin$theta, fit.nbin$SE.theta)
      
# Design matrix for creating new lambda^'s    
  xmat<-model.matrix(fit.nbin)
  for(i in 1:nsims){

    # Generate lambda^'s and thetas    
    mus<-exp(xmat%*%beta.hat[i,])
    
    # Generate new simulated values
    new.y<-rnbinom(nobs, mu = mus, size=theta.hat[i])

    # Count the number of zeros
    zeros.sim[i]<-sum(new.y==0)
  }
hist(zeros.sim, xlab="# of zeros", ylab="Density", main="", col="gray")
abline(v = T, col = "blue")
```

